---

plugins:
  - babel
  - react

env:
  node: true
  browser: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:react/recommended'

rules:
  no-console: 0
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
